Support Nuitka `--onefile` compiled application; Implement ISteamUGC/GetAppDependencies
philippj/SteamworksPy pull request #91
Opened 2023-05-25 14:25 UTC by twstagg

Please let me know what you think!

2023-07-31 21:07 UTC, twstagg commented
Anybody had a chance to look at this? I had other work I wanted to do as well, but this is my first try at this sort of work. Is this acceptable?

2025-08-12 21:34 UTC, philippj requested changes

2025-08-12 21:34 UTC, philippj commented on library/sdk/redist/.gitignore
Gitignore must still be present

2025-08-12 21:34 UTC, philippj commented on steamworks/__init__.py
Revert the change in quotes

2025-08-12 21:34 UTC, philippj commented on steamworks/methods.py
>  STEAMWORKS_METHODS = {
Revert the formatting of the dict to keep readability

2025-12-26 11:17 UTC, philippj commented
#114

2025-12-26 11:17 UTC, closed without merging